AWSTemplateFormatVersion: 2010-09-09
Description: |
  Creates RDS Instance for Application use

Parameters:
  pDBName:
    Description: DB Name
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/clarusway/dbname'

  pPassword:
    Description: DB Password
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/clarusway/password'

Resources:

  rRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: "20"
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: false
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: ApplicationRDS
      DBName: !Ref pDBName
#      DBSecurityGroups:
#        - !Ref DBSecGrp
      Engine: "mysql"
#      EngineVersion: "String"
      MasterUserPassword: !Ref pPassword
      MasterUsername: admin
      MultiAZ: false
      Port: "3306"
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !GetAtt rDBSecGrp.GroupId


  rDBSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow MySQL Traffic
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 3306
        ToPort: 3306
        CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: MySQLSecGroup